name: themed
description: The themed package lets you define a theme with const values, and then, by using some dark Dart magic, go and change them dynamically anyway.
version: 5.0.0
homepage: https://github.com/marcglasberg/themed

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

